### ISSUE TITLE
Cant boot up with 1.21 latest purpur version

### ISSUE THREAD

**Issue by gaRt3n** [mrfdev/advanced-achievements#13]
### 🎆 Advanced Achievements version

v8.0.2

### 🖥 Server version

Purpur 1.21-2276-ver/1.21@72ccfbd (2024-07-28T08:22:53Z) for Minecraft 1.21

### 🚰 Spigot username

gaRt3n

### 𝑾 Wiki read

- [X] I have read the Wiki.

### 📁 Existing issues

- [X] I have searched existing issues.

### 🐛 Description

**Hey there,**
first of all, thanks for maintaining that plugin and keeping it open source,
I wanted to install it on the latest purpur version but on boot up i get these error.
need some halp! thanks! :)

### 📄 Server logs

```
[03:33:20 INFO]: [AdvancedAchievements] Enabling AdvancedAchievements v8.0.2
[03:33:20 ERROR]: Error occurred while enabling AdvancedAchievements v8.0.2 (Is it up to date?)
java.lang.StringIndexOutOfBoundsException: Range [23, 22) out of bounds for length 22
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[?:?]
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865) ~[?:?]
	at java.base/java.lang.String.substring(String.java:2834) ~[?:?]
	at java.base/java.lang.String.substring(String.java:2807) ~[?:?]
	at AdvancedAchievements.jar/com.hm.achievement.module.ServerVersionModule.provideServerVersion(ServerVersionModule.java:19) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.achievement.module.ServerVersionModule_ProvideServerVersionFactory.provideServerVersion(ServerVersionModule_ProvideServerVersionFactory.java:33) ~[AdvancedAchievements.jar:?]
	0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
at AdvancedAchievements.jar/com.hm.achievement.module.ServerVersionModule_ProvideServerVersionFactory.get(ServerVersionModule_ProvideServerVersionFactory.java:25) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.achievement.module.ServerVersionModule_ProvideServerVersionFactory.get(ServerVersionModule_ProvideServerVersionFactory.java:7) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.achievement.utils.FancyMessageSender_Factory.get(FancyMessageSender_Factory.java:26) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.achievement.utils.FancyMessageSender_Factory.get(FancyMessageSender_Factory.java:8) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.achievement.command.executable.HelpCommand_Factory.get(HelpCommand_Factory.java:39) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.achievement.command.executable.HelpCommand_Factory.get(HelpCommand_Factory.java:10) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.dagger.internal.SetFactory.get(SetFactory.java:126) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.dagger.internal.SetFactory.get(SetFactory.java:37) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.dagger.internal.SetFactory.get(SetFactory.java:119) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.dagger.internal.SetFactory.get(SetFactory.java:37) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.dagger.internal.DelegateFactory.get(DelegateFactory.java:36) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.achievement.lifecycle.PluginLoader_Factory.get(PluginLoader_Factory.java:122) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.achievement.lifecycle.PluginLoader_Factory.get(PluginLoader_Factory.java:29) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.dagger.internal.DelegateFactory.get(DelegateFactory.java:36) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.achievement.DaggerAdvancedAchievementsComponent.pluginLoader(DaggerAdvancedAchievementsComponent.java:557) ~[AdvancedAchievements.jar:?]
	at AdvancedAchievements.jar/com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:45) ~[AdvancedAchievements.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.MinecraftServer.lambda$spin$[03:33:20 INFO]: [AdvancedAchievements] Disabling AdvancedAchievements v8.0.2
[03:33:20 ERROR]: Error occurred while disabling AdvancedAchievements v8.0.2
java.lang.NullPointerException: Cannot invoke "com.hm.achievement.lifecycle.PluginLoader.disableAdvancedAchievements()" because "this.pluginLoader" is null
	at AdvancedAchievements.jar/com.hm.achievement.AdvancedAchievements.onDisable(AdvancedAchievements.java:63) ~[AdvancedAchievements.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### ⚙ Configuration

```
none since the plugin won't create a folder.
```

**Comment by Greymagic27** [comment]
I'm unable to reproduce this. Was this using a manually compiled build from this repo?
If not please package your own build by cloning this repo and then running `mvn clean package -U`

I notice that it also says version 8.0.2, however the revision I can see on the pom.xml is 6.0.0

**Comment by gaRt3n** [comment]
Ah i think the issue is, that i used the "last published" jar from here. I'll have a look how to compile it by my self.

**Comment by Greymagic27** [comment]
Yeah that one hasn't been updated in a while.

You just need maven installed and then in the cloned git repo directory, run the command above. It'll output into `advanced-achievements\advanced-achievements-plugin\target` as `AdvancedAchievements.jar`

**Comment by Greymagic27** [comment]
Update: There is now a 1.21.1 published release on this repo so you don't have to self compile. I will be making these for every major MC release going forward.
